services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - 443:443
    volumes:
      - wordpress-data:/var/www/html/
    restart: always
    networks:
      - inception

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    ports:
      - 9000:9000
    restart: always
    volumes:
      - wordpress-data:/var/www/html/
    networks:
      - inception
    build: ./requirements/wordpress/

  mariadb:
    container_name: mariadb
    ports:
      - 3306:3306
    restart: always
    env_file: .env
    volumes:
      - mariadb-data:/var/www/html/
    networks:
      - inception
    build: ./requirements/mariadb/

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rtissera/data/mariadb
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rtissera/data/wordpress

networks:
  inception:
    driver: bridge
