services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    ports:
      - "443:443"
    restart: on-failure
    init: true
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/
    networks:
      - inception
    build: ./requirements/nginx/

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    expose:
      - "9000"
    restart: on-failure
    init: true
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/
    networks:
      - inception
    build: ./requirements/wordpress/

  mariadb:
    container_name: mariadb
    expose:
      - "3306"
    restart: on-failure
    init: true
    env_file:
      - .env
    volumes:
      - mariadb:/var/www/html/
    networks:
      - inception
    build: ./requirements/mariadb/

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/rtissera/data/mariadb'
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/rtissera/data/wordpress'

networks:
  inception:
    driver: bridge
