services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - "443:443"
    # volumes:
    #   - wordpress-data:/var/www/html/
    # depends_on:
    #   - wordpress
    restart: always
    networks:
      - inception

networks:
  inception:
    driver: bridge
