services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - 443:443
    volumes:
      - wordpress-data:/var/www/html/
    restart: always
    networks:
      - inception

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress/
    ports:
      - 443:443
    volumes:
      - wordpress-data:/var/www/html/
    restart: always
    networks:
      - inception

  mariadb:
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - mariadb-data:/var/www/html/
    networks:
      - inception
    ports:
      - 443:443
    build: ./requirements/mariadb/

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/login/rtissera/mariadb
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/login/rtissera/wordpress

networks:
  inception:
    driver: bridge
